on:
  issue_comment:
    types: [ created, deleted, edited ]

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - name: Print comment
        run: echo "评论的内容是 ${{github.event.comment.body}} event: ${{ toJson(github.event) }}"
